version: "3"

services:
  # ① MongoDB 컨테이너
  mongo:
    image: mongo:6
    ports:
      - "27018:27017"          # 호스트:컨테이너
    volumes:
      - ./_data/mongo:/data/db # 로컬 폴더에 DB 파일 영구 저장

  # ② FastAPI 컨테이너
  api:
    build: ./backend           # 위 Dockerfile 이용해 이미지 빌드
    ports:
      - "8000:8000"            # http://localhost:8000
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./backend:/code        # 코드 바로 반영(핫리로드)
      # 대용량 데이터셋 폴더들을 외부에서 마운트 (도커 이미지에 포함하지 않음)
      - ./backend/app/static/DATASET(AirBirds)_Predict:/code/app/static/DATASET(AirBirds)_Predict
      - ./backend/app/static/DATASET(AirBirds)_Predict_original:/code/app/static/DATASET(AirBirds)_Predict_original
    depends_on:
      - mongo                  # mongo가 먼저 떠야 api 시작
